from enum import Enum


class FilePathName(Enum):
    TREASURY_OPI = 'data/treasury/opi'
    RECEIPT_PAGOPA = 'data/receipt/pagopa'
    RECEIPT = 'data/receipt'
    PAYMENTS_REPORTING = 'data/payments_reporting'
    PAYMENTS_REPORTING_PAGOPA = 'data/payments_reporting/pagopa'
    INSTALLMENT = 'data/installment'
    SEND_NOTIFICATION = 'data/send_notification'


class FileStatus(Enum):
    UPLOADED = 'UPLOADED'
    PROCESSING = 'PROCESSING'
    COMPLETED = 'COMPLETED'
    ERROR = 'ERROR'
    WARNING = 'WARNING'


class IngestionFlowFileType(Enum):
    RECEIPT = 'RECEIPT'
    RECEIPT_PAGOPA = 'RECEIPT_PAGOPA'
    PAYMENTS_REPORTING = 'PAYMENTS_REPORTING'
    PAYMENTS_REPORTING_PAGOPA = 'PAYMENTS_REPORTING_PAGOPA'
    TREASURY_OPI = 'TREASURY_OPI'
    DP_INSTALLMENTS = 'DP_INSTALLMENTS'
    SEND_NOTIFICATION = 'SEND_NOTIFICATION'


class FileOrigin(Enum):
    PAGOPA = 'PAGOPA'
    SIL = 'SIL'
    PORTAL = 'PORTAL'


class ReceiptOriginType(Enum):
    RECEIPT_PAGOPA = 'RECEIPT_PAGOPA'
    RECEIPT_FILE = 'RECEIPT_FILE'
    PAYMENTS_REPORTING = 'PAYMENTS_REPORTING'

class SilExportStatus:
  EXPORT_STATUS_COMPLETED = 'EXPORT_ESEGUITO'
  EXPORT_STATUS_NO_DATA = 'EXPORT_ESEGUITO_NESSUN_DOVUTO_TROVATO'
  EXPORT_STATUS_IN_PROGRESS = ('LOAD_EXPORT', 'EXPORT_IN_ELAB')
  EXPORT_STATUS_FAILED = ('ERROR_EXPORT', 'EXPORT_CANCELLATO')

class SilImportStatus:
  IMPORT_STATUS_COMPLETED = 'FILE_CARICATO'
  IMPORT_STATUS_IN_PROGRESS = ('FILE_SCARICATO', 'FILE_IN_CARICAMENTO')
  IMPORT_STATUS_FAILED = 'ERROR_LOAD'