SECRETS_PATH: "config/pu_feature_secrets.yaml"
TARGET_ENV: "dev"
default_timeout: 5000
API_KEY_HEADER: "Ocp-Apim-Subscription-Key"
api:
  base_path:
    payhub: "https://hub.internal.dev.p4pa.pagopa.it/payhub"
    internal: "https://hub.internal.dev.p4pa.pagopa.it"
    io_notification: "https://hub.internal.dev.p4pa.pagopa.it/p4paionotification/ionotification"
    gpd: "https://api.uat.platform.pagopa.it/gpd/debt-positions-service/v1"
  path_root:
    public: "/public"
    app_admin: "/appadmin"
    operatore: "/operatore"
    operatore_admin: "/operatore/admin"
ente:
  status:
    inserito: 'INSERITO'
    pre-esercizio: 'PRE-ESERCIZIO'
    esercizio: 'ESERCIZIO'
  tipo:
    comune: 'COMUNE'
    provincia: 'PROVINCIA'
    regione: 'REGIONE'
  funzionalita:
    avviso_digitale: 'AVVISO_DIGITALE'
    ente_pubblico: 'ENTE_PUBBLICO'
    esito_push: 'INOLTRO_ESITO_PAGAMENTO_PUSH'
    avviso_io: 'NOTIFICA_AVVISI_IO'
    pagamento_spontaneo: 'PAGAMENTO_SPONTANEO'
ente_data:
  enteE:
    cod_ipa: 'FEATURE_TEST_E'
    name: 'Ente Feature Test E'
    email: 'entefeaturetestE@email.it'
    application_code: '0E'
    tipo: 'Comune'
  enteF:
    cod_ipa: 'FEATURE_TEST_F'
    name: 'Ente Feature Test F'
    email: 'entefeaturetestF@email.it'
    application_code: '0F'
    tipo: 'Comune'
