SECRETS_PATH: "config/pu_feature_secrets.yaml"
TARGET_ENV: "dev"
default_timeout: 5000
API_KEY_HEADER: "Ocp-Apim-Subscription-Key"
SOAP_ACTION_HEADER: "SOAPAction"
BROKER_ID_HEADER: "brokerId"
api:
  base_path:
    gpd: "https://api.uat.platform.pagopa.it/gpd/debt-positions-service/v1"
    nodo_psp: "https://api.uat.platform.pagopa.it/nodo/node-for-psp/v1"
  ingress_path:
    debt_positions: "/p4padebtpositions"
    debt_position_type_org_crud: "/p4padebtpositions/crud/debt-position-type-orgs/search"
    workflow_hub: "/p4paworkflowhub/workflowhub/workflows"
    organization_crud: "/p4paorganization/crud/organizations/search"
    process_executions_crud: "/p4paprocessexecutions/crud/ingestion-flow-files/search"