SECRETS_PATH: "config/pu_feature_secrets.yaml"
TARGET_ENV: "dev"
default_timeout: 5000
API_KEY_HEADER: "Ocp-Apim-Subscription-Key"
SOAP_ACTION_HEADER: "SOAPAction"
api:
  base_path:
    gpd: "https://api.uat.platform.pagopa.it/gpd/debt-positions-service/v1"
    nodo_psp: "https://api.uat.platform.pagopa.it/nodo/node-for-psp/v1"
  ingress_path:
    bff: "/p4papubff/bff"
    debt_positions: "/p4padebtpositions"
    debt_position_type_org_crud: "/p4padebtpositions/crud/debt-position-type-orgs/search"
    workflow_hub: "/p4paworkflowhub/workflowhub/workflows"
    organization_crud: "/p4paorganization/crud/organizations/search"
    process_executions_crud: "/p4paprocessexecutions/crud/ingestion-flow-files/search"
    classifications: "/p4paclassification"
    fileshare: "/p4pafileshare"
    send_notification: "/p4pasendnotification/p4pasend"
debt_position_type_org_code:
  feature_test: "FEATURE_TEST"
  feature_test_2: "FEATURE_TEST_2"