parameters:
  - name: env
    type: string

  - name: tag
    type: string

steps:
  - script: |
      python3 --version
      pip3 --version
    displayName: "Display Python version"
  - script: |
      python3 --version
      python3 -m pip install --user pipenv
      python3 -m pipenv sync
    displayName: "Install requirements"
  - task: DownloadSecureFile@1
    name: pu_feature_secrets
    displayName: 'Download PU secrets'
    inputs:
      secureFile: 'pu_feature_secrets.yaml'
  - script: |
      python3 -m pipenv run behave --junit --junit-directory "tests/reports/behave" --tags "${{ parameters.tag }}"
    displayName: 'Run tests with Behave'
    env:
      PU_SECRETS_PATH: $(pu_feature_secrets.secureFilePath)
      PU_TARGET_ENV: ${{ parameters.env }}
    continueOnError: true
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'tests/reports/behave/*.xml'
      searchFolder: $(Build.SourcesDirectory)
      failTaskOnFailedTests: true
      testRunTitle: 'Feature test results: ${{ parameters.tag }}'
    continueOnError: true
  - task: Bash@3
    displayName: 'Send message on Slack'
    condition: in(variables['Agent.JobStatus'], 'SucceededWithIssues', 'Failed')
    inputs:
      targetType: 'inline'
      script: >
        curl -X POST \
          -H "Content-type: application/json" \
          --data '{"text": "*Attention: There is an error in p4pa-pu-feature-test while running the tests!*\nCheck the logs for more details $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId) to view the results."}' \
          $(TEST_SLACK)
